### ISSUE TITLE
peer to peer code review

### ISSUE THREAD

**Issue by olanikegloria** [Shabiblac/Microverse-Portfolio-Design#12]
I suggest that the border-radius for the hero section to be reduced or padding should be added as required

**Comment by Kgomotso196** [comment]
Kindly, consider adding the MIT file provided when you include the microverse README.md when creating your repository.

**Comment by Rifat8080** [comment]
![shabi p2p review](https://user-images.githubusercontent.com/123451855/237025698-0091f791-ffca-4a81-9ecb-6e3c49525aa5.png)
It would be better I think if you add some transition to your portfolio sections card images, so that your projects UI looks more attractive.

**Comment by olanikegloria** [comment]
In summary I think the work is really good and all the suggestions should be noted
